instructblip_selection_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
  result_names:
    - "Likelihood"
    - "Likelihood + ICL"
    - "Coherence"
    - "Coherence + ICL"
  colors:
    - '#C10000'
    - '#C100C1'
    - '#0000C1'
    - '#00C1C1'
llava_selection_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
  result_names:
    - "Likelihood"
    - "Likelihood + ICL"
    - "Coherence"
    - "Coherence + ICL"
  colors:
    - '#C10000'
    - '#C100C1'
    - '#0000C1'
    - '#00C1C1'
llama3_selection_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
  result_names:
    - "Likelihood"
    - "Likelihood + ICL"
    - "Coherence"
    - "Coherence + ICL"
  colors:
    - '#C10000'
    - '#C100C1'
    - '#0000C1'
    - '#00C1C1'
llava_generation_icl_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"    
  result_names:
    - "Likelihood"
    - "Likelihood + ICL"
    - "Coherence"
    - "Coherence + ICL"
  colors:
    - '#C10000'
    - '#C100C1'
    - '#0000C1'
    - '#00C1C1'
llava_generation_base_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
  result_names:
    - "Likelihood"
    - "Likelihood + ICL"
    - "Coherence"
    - "Coherence + ICL"
  colors:
    - '#C10000'
    - '#C100C1'
    - '#0000C1'
    - '#00C1C1'
llava_generation_icl_lp_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
  result_names:
    - "Likelihood"
    - "Likelihood + ICL"
    - "Coherence"
    - "Coherence + ICL"
  colors:
    - '#C10000'
    - '#C100C1'
    - '#0000C1'
    - '#00C1C1'    
llava_generation_base_lp_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
    - "/path/to/corresponding/results/directory/outputs_val.json"
  result_names:
    - "Likelihood"
    - "Likelihood + ICL"
    - "Coherence"
    - "Coherence + ICL"
  colors:
    - '#C10000'
    - '#C100C1'
    - '#0000C1'
    - '#00C1C1'
gpt4o_val:
  outputs_fnames:
    - "/path/to/corresponding/results/directory/outputs_val.json"
  result_names:
    - "Likelihood"
  colors:
    - '#C10000'
