hf_token: "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"
random_seed: 222
cache:
  data_cache_dir: "/nfs/turbo/coe-chaijy/zheyuan/simulation_informed_pcr4nlu/TRAVEl_cache_dir"
  model_cache_dir: "/scratch/chaijy_root/chaijy0/zheyuan/.cache/huggingface"
  cache_frequency: 50
  results_dir: "saved_results"
data:
  video_frame_sampling_frequency: 2
  video_frame_dimension: 400
  images_chunk_size: 500
  captaincook4d:
    annotations_dir: "/nfs/turbo/coe-chaijy-unreplicated/datasets/captaincook4d/annotations"
    video_dir: "/nfs/turbo/coe-chaijy-unreplicated/datasets/captaincook4d/data/captain_cook_4d/hololens/sync/pv"
  ego4d:
    annotation_path: "/nfs/turbo/coe-chaijy-unreplicated/datasets/ego4d/v2/annotations/fho_main.json"
    sampled_frames_path: "/nfs/turbo/coe-chaijy/generated-data/ego4d/v2/"
    split_path: "/nfs/turbo/coe-chaijy/generated-data/ego4d/v2/splits"
    video_path: "/nfs/turbo/coe-chaijy-unreplicated/datasets/ego4d/v2/full_scale"
    mismatch_dir: "/nfs/turbo/coe-chaijy/zheyuan/simulation_informed_pcr4nlu/TRAVEl/ego4d_mismatch_srl_files"
    mismatch_count: 3
grounding:
  owlv2_path: "google/owlv2-base-patch16"
  owl_threshold: 0.2
  owl_batch_size: 32
mistake_detection_strategies:
    target_frames_proportion: 0.1
