cache:
  data_cache_dir: "cache_dir"
  model_cache_dir: "/scratch/chaijy_root/chaijy0/sstorks/.cache/huggingface"
captaincook4d:
  annotations_dir: "/nfs/turbo/coe-chaijy-unreplicated/datasets/captaincook4d/annotations"
  video_dir: "/nfs/turbo/coe-chaijy-unreplicated/datasets/captaincook4d/data/captain_cook_4d/hololens/sync/pv"