hf_token: "hf_XXXXXXXX"
random_seed: 222
cache:
  data_cache_dir: "/path/to/cached/ego4d_pmd_data"
  model_cache_dir: "/path/to/custom/hf/cache/dir/.cache/huggingface"
  cache_frequency: 50
  results_dir: "saved_results_222"
data:
  video_frame_dimension: 600
  video_frame_dimension_cache: 300
  images_chunk_size: 200
  qualtrics_api_token: ""
  qualtrics_data_center: ""
  qualtrics_library_name: ""
  ego4d:
    video_frame_keep_frequency: 1.0
    video_frame_min_brightness: 0.2
    annotation_path: "/path/to/ego4d/v2/annotations/fho_main.json"
    split_path: "./ego4d_splits"
    video_path: "/path/to/videos/in/ego4d/v2/full_scale"
    misalignsrl_path: "/path/to/ego4d/misalignsrl_more_samples_same_split_combinedwords_wohand_objectstatesafe.parquet"
  captaincook4d:
    annotations_dir: "/path/to/captaincook4d/annotations"
    video_dir: "/path/to/captaincook4d/data/captain_cook_4d/hololens/sync/pv"
    video_frame_sampling_frequency: 10
    video_frame_keep_frequency: 2.0    
vqg:
  nli_correction_minimum_confidence: 0.8
grounding:
  owlv2_path: "google/owlv2-base-patch16"
  owl_threshold: 0.25
  owl_batch_size: 60
  mask_strength: 1.0
  minimum_crop_size: 50
  maximum_bboxes_per_object: 3
mistake_detection_strategies:
  ema_tau: 2.0
  frames_proportion: 1.0
  nli_model_path: "facebook/bart-large-mnli"
  nli_batch_size: 128
  nli_relevance_delta: 0.2
  nli_rerun_on_relevant_evidence: false
  nli_replace_probs: false
  diversity_model_path: "sentence-transformers/all-MiniLM-L6-v2"
