hf_token: "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"
random_seed: 222
cache:
  data_cache_dir: "/nfs/turbo/coe-chaijy/sstorks/simulation_informed_pcr4nlu/TRAVEl_generated_data_0808"
  model_cache_dir: "/scratch/chaijy_root/chaijy0/sstorks/.cache/huggingface"
  cache_frequency: 50
  results_dir: "saved_results_222_dpo1028"
data:
  video_frame_dimension: 600
  video_frame_dimension_cache: 300
  images_chunk_size: 200
  captaincook4d:
    annotations_dir: "/nfs/turbo/coe-chaijy-unreplicated/datasets/captaincook4d/annotations"
    video_dir: "/nfs/turbo/coe-chaijy-unreplicated/datasets/captaincook4d/data/captain_cook_4d/hololens/sync/pv"
    video_frame_sampling_frequency: 10
    video_frame_keep_frequency: 2.0
  ego4d:
    video_frame_keep_frequency: 1.0
    video_frame_min_brightness: 0.2
    annotation_path: "/nfs/turbo/coe-chaijy-unreplicated/datasets/ego4d/v2/annotations/fho_main.json"
    split_path: "/nfs/turbo/coe-chaijy/generated-data/ego4d/v2/splits"
    video_path: "/nfs/turbo/coe-chaijy-unreplicated/datasets/ego4d/v2/full_scale"
    misalignsrl_path: "/home/sstorks/coe-chaijy/sstorks/simulation_informed_pcr4nlu/TRAVEl/ego4d_mismatch_srl_files/misalignsrl_more_samples_same_split_combinedwords_wohand_objectstatesafe.parquet"
  epickitchens:
    annotation_path_train: "/nfs/turbo/coe-chaijy-unreplicated/datasets/EPIC-KITCHENS/epic-kitchens-100-annotations/EPIC_100_train.csv"
    annotation_path_val: "/nfs/turbo/coe-chaijy-unreplicated/datasets/EPIC-KITCHENS/epic-kitchens-100-annotations/EPIC_100_validation.csv"
    annotation_path_test: "/nfs/turbo/coe-chaijy-unreplicated/datasets/EPIC-KITCHENS/epic-kitchens-100-annotations/EPIC_100_test.csv"
    video_path: "/nfs/turbo/coe-chaijy-unreplicated/datasets/EPIC-KITCHENS/EPIC-KITCHENS/"
vqg:
  nli_correction_minimum_confidence: 0.8
grounding:
  owlv2_path: "google/owlv2-base-patch16"
  owl_threshold: 0.25
  owl_batch_size: 60
  mask_strength: 1.0
  minimum_crop_size: 50
  maximum_bboxes_per_object: 3
mistake_detection_strategies:
  ema_tau: 2.0
  frames_proportion: 1.0
  nli_model_path: "facebook/bart-large-mnli"
  nli_batch_size: 128
  nli_relevance_delta: 0.2
  nli_rerun_on_relevant_evidence: false
  nli_replace_probs: false
